---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: uwu-os
# description will be included in the image's metadata
description: UwU spin of Fedora Atomic.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/rakuos/rakuos-base
image-version: latest # You can pin to a specific version of Fedora as well


# platforms to build for
platforms:
  - linux/amd64
  - linux/amd64/v2

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - name: atim/starship
          chroot: fedora-43-x86_64
    install:
      packages:
        - micro
        - starship
        - fish 
        - noctalia
        - labwc
        - nvim
        - fastfetch
    remove:
      packages:
        - rakuos-branding
        - podman
        - podman-compose

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - app.zen_browser.zen 
          - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages
  - type: fonts
    fonts:
      nerd-fonts:
        - IosevkaTerm
        - DepartureMono
        - Monofur
        - MPlus

  - type: script
    snippets:
        - "git clone https://github.com/LazyVim/starter ~/.config/nvim"

  - type: brew
    nofile-limits: true

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
